
% import the csv files
[x,z] = importData(50, 0 ...
    ,'Standing'...
    ,'Downstairs'...
    ,'Upstairs'...
    ,'Brushing'...
    ,'Clapping'...
    ,'Eating'...
    ,'Hitting'...
    ,'Jumping'...
    ,'Running'...
    ,'Computer'...
    ,'Walking'...
    ,'Waving' ...
    );

% Uncomment to convert feature set to focus on the target behaviours
% x = convert2dualclass(x, 'Brushing', 'Hitting');

% uncomment to export data to csv
% writetable(x, strcat('bin-BrushHit-', num2str(windowSize),'-',num2str(overlap) ,'.csv'));



